version: '3'

services:
  postgres:
      image: postgres:16.3
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ap1rickmorty
        POSTGRES_DB: rickmortydata
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
